#Challenge 1: Test
version: '3.8'

services:
  frontend:
    image: httpd:latest
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      webnet:
        ipv4_address: 172.28.1.2
        aliases:
          - frontend
    depends_on:
      - backend

  lfi-challenge:
    build: ./lfi-challenge
    networks:
      webnet:
        ipv4_address: 172.28.1.3
        aliases:
          - lfi-challenge
  
  webhook-container:
    build: "./Webhook Container"
    networks:
      webnet:
        ipv4_address: 172.28.1.6
        aliases:
          - webhook-container
    volumes:
      - ./Webhook Container:/usr/src/app

  backend:
    image: python:3.8-slim
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
    networks:
      webnet:
        ipv4_address: 172.28.1.4
        aliases:
          - backend

  bruteforce-ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=admin #optional
    ports:
      - 2222:2222
    restart: unless-stopped
    networks:
      webnet:
        ipv4_address: 172.28.1.8
    volumes:
      - ./bruteforce-ssh:/config

  kali:
    build: ./kali
    networks:
      webnet:
        ipv4_address: 172.28.1.5
        aliases:
          - kali
    command: tail -f /dev/null # Keep the container running

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

