version: '3.8'

services:
  frontend:
    image: httpd:latest
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      webnet:
        ipv4_address: 172.28.1.2
        aliases:
          - frontend
    depends_on:
      - backend

  lfi-challenge:
    build: ./lfi-challenge
    networks:
      webnet:
        ipv4_address: 172.28.1.3
        aliases:
          - lfi-challenge
    depends_on:
      - backend

  backend:
    image: python:3.8-slim
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
    networks:
      webnet:
        ipv4_address: 172.28.1.4
        aliases:
          - backend

  kali:
    build: ./kali
    networks:
      webnet:
        ipv4_address: 172.28.1.5
        aliases:
          - kali
    command: tail -f /dev/null # Keep the container running

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

