# Use a base image with vsftpd and Docker installed
FROM delfer/alpine-ftp-server

COPY vsftpd.conf /etc/vsftpd/vsftpd.conf
# Configure vsftpd
RUN mkdir -p /secure \
    && mkdir -p /ftp/upload \
    && echo "COMPLETION SCRIPT" > /secure/flag.sh \
    && chmod 700 /secure \
    && chmod -R 777 /ftp/upload \
    && chown ftp:ftp /ftp/upload -R

