version: '3.8'

services:
  frontend:
    image: httpd:latest
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - backend

  backend:
    image: python:3.8-slim
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - webnet

  webhookcontainer:
    build: "../Webhook Container"
    ports:
      - "3000:3000"

  kali:
    build: ./kali
    networks:
      - webnet
    command: tail -f /dev/null # Keep the container running

networks:
  webnet:
