#Challenge 3: FTP Fumble
version: "3.8"

networks:
  webnet:
    driver: bridge
    name: webnet
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

services:
  ftp-server:
    container_name: my-ftp-server
    build: ../FTP-Server
    environment:
      - USERS=one|1234
      - FTP_USER=user
    #Step 1: Allow anon login
    #Step 2: Create /secure directory
    #Step 3: Create completion script inside /secure
    #Step 4: Run script to rebuild dockerfile
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    networks:
      webnet:
        ipv4_address: 172.28.1.6
        aliases:
          - ftp

  kali:
    build: ../kali
    container_name: kali
    depends_on: 
      - ftp-server
    networks:
      webnet:
        ipv4_address: 172.28.1.5
        aliases:
          - kali
    command: tail -f /dev/null # Keep the container running

